from pathlib import Path
import re
p=Path('/mnt/data/snowball_avalanche.html')
s=p.read_text(encoding='utf-8')
# Version bump
s=s.replace('Snowball Avalanche — Infinite World v1.3','Snowball Avalanche — Infinite World v1.4')
s=s.replace('Infinite World v1.3','Infinite World v1.4')
s=s.replace('Snowball Avalanche Infinite World v1.3: PASS','Snowball Avalanche Infinite World v1.4: PASS')

start=s.index('function updateFx(dt){')
end=s.index('function showGameOver', start)
new_block=r'''function updateFx(dt){for(let q of fx){q.life-=dt;q.x+=q.vx*dt;q.y+=q.vy*dt;let grav=q.type==='deathSnow'?205:q.type==='deathRock'?275:q.type==='deathDust'?90:q.type==='debris'?65:q.type==='spark'?35:-8;q.vy+=grav*dt;q.vx*=q.type==='deathSnow'?.98:q.type==='deathRock'?.986:.992;q.size+=q.type==='smoke'||q.type==='deathDust'?dt*4.2:0;if((q.type==='deathSnow'||q.type==='deathRock')&&deathCrash&&q.y>deathCrash.surfaceY-q.size*.42){q.y=deathCrash.surfaceY-q.size*.42;if(Math.abs(q.vy)>22){q.vy*=-q.type==='deathRock'?.29:.2;q.vx*=.7}else q.vy=0}}fx=fx.filter(q=>q.life>0)}
function deathImpactBurst(finalHit=false){if(!deathCrash)return;let d=deathCrash,energy=Math.min(1.75,.55+d.startSpeed/460+p.r/330),count=finalHit?Math.min(IS_MOBILE?42:70,Math.round(12+p.r*.28+d.startSpeed*.035)):Math.min(IS_MOBILE?20:32,Math.round(7+p.r*.12));for(let i=0;i<count;i++){let side=(i/(Math.max(1,count-1)))*2-1,spread=(.25+Math.abs(side)*.75),snow=!finalHit||i%7!==0;fx.push({type:snow?'deathSnow':'deathRock',x:p.x+side*p.r*rnd(.12,.72),y:d.surfaceY-rnd(0,Math.max(2,p.r*.08)),vx:side*rnd(35,finalHit?175:105)*energy+rnd(-12,12),vy:-rnd(finalHit?42:25,finalHit?150:88)*energy*spread,size:rnd(1.4,Math.max(2.5,p.r*(finalHit?.065:.035))),life:rnd(.55,finalHit?1.55:.95),c:snow?(i%3?'#f5fdff':'#badce4'):(i%2?'#526168':'#7d898d')})}for(let i=0;i<(finalHit?Math.min(24,7+p.r/7):Math.min(10,3+p.r/14));i++)fx.push({type:'deathDust',x:p.x+rnd(-p.r*.55,p.r*.55),y:d.surfaceY-rnd(0,3),vx:rnd(-28,28),vy:-rnd(18,finalHit?70:42),size:rnd(2,Math.max(4,p.r*.065)),life:rnd(.38,finalHit?.95:.62),c:'#fff'});shake=Math.max(shake,finalHit?Math.min(24,9+p.r*.05+d.startSpeed*.018):Math.min(13,5+p.r*.025+d.startSpeed*.009));tone(finalHit?48:74,finalHit?.22:.11,finalHit?'sawtooth':'triangle',finalHit?.055:.035)}
function spawnDeathShards(){if(!deathCrash||deathCrash.shattered)return;let d=deathCrash;d.shattered=true;let count=Math.min(IS_MOBILE?95:165,Math.round(32+p.r*.68+d.startSpeed*.09)),energy=Math.min(1.9,.72+d.startSpeed/410+p.r/285);for(let i=0;i<count;i++){let a=(i/count)*TAU+rnd(-.18,.18),rad=rnd(0,p.r*.8),snow=i%10!==0;fx.push({type:snow?'deathSnow':'deathRock',x:p.x+Math.cos(a)*rad*.66,y:d.surfaceY-Math.abs(Math.sin(a))*rad*.18-rnd(0,p.r*.1),vx:Math.cos(a)*rnd(48,205)*energy+d.startVX*.08,vy:-rnd(75,245)*energy-Math.abs(Math.sin(a))*60,size:rnd(Math.max(1.5,p.r*.022),Math.max(3.2,p.r*.105)),life:rnd(1.25,2.45),c:snow?(i%5?'#f3fdff':'#b8dbe2'):(i%2?'#56656b':'#899397')})}deathImpactBurst(true);for(let i=0;i<Math.min(38,12+p.r/4.5);i++)fx.push({type:'deathDust',x:p.x+rnd(-p.r*.72,p.r*.72),y:d.surfaceY-rnd(0,p.r*.18),vx:rnd(-45,45),vy:rnd(-82,-18),size:rnd(3,Math.max(6,p.r*.085)),life:rnd(.7,1.35),c:'#fff'});marks.push({kind:'impact',x:p.x,y:d.surfaceY+1,size:Math.max(20,p.r*.78),life:2.8,c:'#8dafb8'});for(let k=0;k<6;k++){let a=(-.86+k*.34)+rnd(-.05,.05),len=Math.max(18,p.r*(.48+rnd(0,.42)));marks.push({kind:'crack',x:p.x,y:d.surfaceY+1,size:len,angle:a,c:'#536a72',life:3})}shake=Math.min(30,12+p.r*.06+d.startSpeed*.026);tone(42,.3,'square',.03)}
function beginDeathCrash(reason='life'){if(state==='crash'||state==='over')return;saveLocalRecord();flushShared();statActive=false;state='crash';music('off');input.x=0;input.y=1;input.keys={};$('#touch').classList.add('hidden');$('#pauseBtn').classList.add('hidden');let gap=Math.max(72/camera.finalZoom,p.r*.32),surfaceY=p.y+p.r*.8+gap,impactY=surfaceY-p.r*.74,seed=hashSeed(worldState.seed,Math.round(p.x),Math.round(worldState.absoluteDistance));let rr=seededRandom(seed),surface=[];for(let i=0;i<=26;i++)surface.push((rr()-.5)*Math.max(3,6/camera.finalZoom));let cracks=[];for(let i=0;i<13;i++)cracks.push({x:(i+.35)/13,lean:(rr()-.5)*28/camera.finalZoom,depth:.28+rr()*.62});deathCrash={reason,t:0,approachEnd:.62,reboundEnd:.94,secondHit:1.18,shatterAt:1.31,endAt:2.8,startX:p.x,startY:p.y,surfaceY,impactY,startSpeed:p.speed,startVX:p.vx,shattered:false,firstHit:false,secondHitDone:false,squeeze:0,crackAmount:0,surface,cracks,bounceHeight:Math.min(Math.max(10,p.r*.18),34/camera.finalZoom),settleX:p.x};msg(cfg.lang==='pt-BR'?'A ENCOSTA ACABOU!':'THE SLOPE ENDS!');tone(112,.1,'triangle',.028)}
function updateDeathCrash(dt){if(!deathCrash)return;let d=deathCrash;d.t+=dt;let t=d.t,prevX=p.x;d.squeeze=0;d.crackAmount=0;if(t<d.approachEnd){let u=clamp(t/d.approachEnd,0,1),fall=u*u*(2-u);p.y=lerp(d.startY,d.impactY,fall);p.x=d.startX+d.startVX*t*(1-u*.52);p.roll+=Math.max(.08,d.startSpeed/Math.max(20,p.r))*dt*(.86-.28*u)*p.rollDir;p.heading*=Math.max(0,1-dt*1.45);shake=Math.max(shake,.7+u*3.2)}else if(t<d.reboundEnd){if(!d.firstHit){d.firstHit=true;d.settleX=p.x;deathImpactBurst(false);tone(86,.09,'square',.028)}let u=clamp((t-d.approachEnd)/(d.reboundEnd-d.approachEnd),0,1),arc=Math.sin(u*Math.PI);p.y=d.impactY-d.bounceHeight*arc;p.x=d.settleX+d.startVX*.035*Math.sin(u*Math.PI*.8);p.roll+=d.startSpeed/Math.max(25,p.r)*dt*.23*p.rollDir;d.squeeze=(1-u)*.38;d.crackAmount=.18+.2*u;shake=Math.max(shake,(1-u)*8)}else if(t<d.secondHit){let u=clamp((t-d.reboundEnd)/(d.secondHit-d.reboundEnd),0,1),fall=u*u;p.y=lerp(d.impactY-d.bounceHeight*.08,d.impactY,fall);p.x=lerp(p.x,d.settleX+d.startVX*.012,u);p.roll+=d.startSpeed/Math.max(28,p.r)*dt*.12*p.rollDir;d.squeeze=.05+.16*u;d.crackAmount=.4+.32*u}else{p.y=d.impactY;p.x=d.settleX+d.startVX*.012;if(!d.secondHitDone){d.secondHitDone=true;deathImpactBurst(true);tone(57,.16,'sawtooth',.045)}let u=clamp((t-d.secondHit)/(d.shatterAt-d.secondHit),0,1);d.squeeze=.22+.5*Math.sin(u*Math.PI*.72);d.crackAmount=.72+.28*u;if(t>=d.shatterAt&&!d.shattered)spawnDeathShards()}if(!d.shattered&&Math.abs(p.x-prevX)>0)p.heading+=(Math.atan2(p.x-prevX,Math.max(.001,Math.abs(p.y-d.startY)+1))-p.heading)*Math.min(1,dt*3);updateFx(dt);shake=Math.max(0,shake-16*dt);if(t>=d.endAt)showGameOver(d.reason)}
function drawDeathSurface(){if(!deathCrash)return;let d=deathCrash,b=camera.bounds||getCameraBounds(),y=d.surfaceY,w=b.width*1.4,x=b.left-b.width*.2,rockH=Math.max(48/camera.finalZoom,p.r*.3),pts=d.surface||[];g.save();g.fillStyle='#465258';g.beginPath();g.moveTo(x,y+rockH);g.lineTo(x,y+4);for(let i=0;i<pts.length;i++){let xx=x+w*i/Math.max(1,pts.length-1);g.lineTo(xx,y+pts[i])}g.lineTo(x+w,y+rockH);g.closePath();g.fill();let snowH=Math.max(7/camera.finalZoom,p.r*.035);g.fillStyle='#e8f8fb';g.beginPath();g.moveTo(x,y+2);for(let i=0;i<pts.length;i++){let xx=x+w*i/Math.max(1,pts.length-1);g.lineTo(xx,y+pts[i]-snowH*.46)}g.lineTo(x+w,y+snowH);g.lineTo(x,y+snowH);g.closePath();g.fill();g.strokeStyle='#263137';g.lineWidth=Math.max(1,1.7/camera.finalZoom);g.globalAlpha=.76;for(let c of d.cracks||[]){let xx=x+w*c.x,yy=y+4;g.beginPath();g.moveTo(xx,yy);g.lineTo(xx+c.lean,yy+rockH*c.depth);g.lineTo(xx+c.lean*1.35+(c.x>.5?8:-8)/camera.finalZoom,yy+rockH*Math.min(.95,c.depth+.15));g.stroke()}g.globalAlpha=1;if(d.firstHit){let pulse=clamp((d.t-d.approachEnd)/.34,0,1),r=Math.max(14,p.r*(.55+pulse*.55));g.strokeStyle='#a7ccd5';g.lineWidth=Math.max(1,2.2/camera.finalZoom);g.globalAlpha=(1-pulse)*.68;g.beginPath();g.ellipse(d.settleX,y+1,r*1.45,r*.24,0,0,TAU);g.stroke();g.globalAlpha=1}g.restore()}
'''
s=s[:start]+new_block+s[end:]
# Replace snowball crash deformation expression only
old="crashU=state==='crash'&&deathCrash?Math.max(0,Math.min(1,(deathCrash.t-deathCrash.impactAt)/Math.max(.001,deathCrash.shatterAt-deathCrash.impactAt))):0;"
new="crashU=state==='crash'&&deathCrash?(deathCrash.squeeze||0):0,crashCracks=state==='crash'&&deathCrash?(deathCrash.crackAmount||0):0;"
if old not in s:
    raise SystemExit('snowball crashU pattern not found')
s=s.replace(old,new,1)
# make scaling reflect squeeze more plausibly and cracks based on crack amount
s=s.replace("if(crashU)g.scale(1+crashU*.34,1-crashU*.46);","if(crashU)g.scale(1+crashU*.28,Math.max(.5,1-crashU*.42));",1)
s=s.replace("if(crashU>.12){g.strokeStyle='#698d96';g.lineWidth=Math.max(1,base*.025);g.globalAlpha=.45+.5*crashU;for(let k=0;k<6;k++){let a=-Math.PI*.82+k*.31+Math.sin(k*8.1)*.08,len=base*(.25+.28*crashU);", "if(crashCracks>.08){g.strokeStyle='#698d96';g.lineWidth=Math.max(1,base*.025);g.globalAlpha=.32+.62*crashCracks;for(let k=0;k<7;k++){let a=-Math.PI*.86+k*.285+Math.sin(k*8.1)*.08,len=base*(.18+.42*crashCracks);",1)
s=s.replace("let plume=state==='crash'?Math.max(0,Math.round((1-crashU)*Math.min(IS_MOBILE?14:22,4+base/6))):", "let plume=state==='crash'?Math.max(0,Math.round((1-Math.min(1,crashCracks))*Math.min(IS_MOBILE?14:22,4+base/6))):",1)
# marks render support crack type
oldmark="if(m.kind==='impact'){g.fillStyle=m.c;g.beginPath();g.ellipse(m.x,m.y,m.size*1.5,m.size*.65,0,0,TAU);g.fill()}else{px(m.x,m.y,m.size*1.5,m.size,m.c)}"
newmark="if(m.kind==='impact'){g.fillStyle=m.c;g.beginPath();g.ellipse(m.x,m.y,m.size*1.5,m.size*.65,0,0,TAU);g.fill()}else if(m.kind==='crack'){g.strokeStyle=m.c;g.lineWidth=Math.max(worldPixelSize(),1.5/camera.finalZoom);g.beginPath();g.moveTo(m.x,m.y);g.lineTo(m.x+Math.cos(m.angle||0)*m.size,m.y+Math.sin(m.angle||0)*m.size*.35);g.stroke()}else{px(m.x,m.y,m.size*1.5,m.size,m.c)}"
if oldmark not in s: raise SystemExit('mark pattern not found')
s=s.replace(oldmark,newmark,1)
# update assertion/info text
s=s.replace("console.assert(typeof handleEscaped==='function'&&typeof recoverLife==='function','survival life loop');", "console.assert(typeof handleEscaped==='function'&&typeof recoverLife==='function','survival life loop');console.assert(typeof beginDeathCrash==='function'&&typeof spawnDeathShards==='function','two-stage death crash');",1)
s=s.replace("natural snow growth, verified survival death path, polished HUD/UI", "natural snow growth, two-stage impact death, polished HUD/UI",1)
p.write_text(s,encoding='utf-8')
print('patched', len(s))
